[package]
name = "adventofcode20-01"
version = "0.1.0"
authors = ["manuel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "adventofcode20-01"
path = "main.rs"
